# Generated by Django 4.1 on 2022-08-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_file_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploadedFile',
            field=models.FileField(upload_to='Uploaded Files/'),
        ),
    ]
