# Generated by Django 4.1 on 2022-08-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_file_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.CharField(default='admin', max_length=200, null=True),
        ),
    ]
