# Generated by Django 4.1 on 2022-08-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_file_filename_alter_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='revision',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
