# Generated by Django 4.1 on 2022-08-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_file_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='revision',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
