# Generated by Django 4.1 on 2022-08-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_file_revision_alter_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploadedFile',
            field=models.FileField(upload_to='UploadedFiles/'),
        ),
    ]
